# Generated by Django 4.2.6 on 2023-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_post_main_post_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="section",
            field=models.CharField(
                choices=[
                    ("Popular", "Popular"),
                    ("Recent", "Recent"),
                    ("Editors_pick", "Editors_pick"),
                    ("Trending", "Trending"),
                    ("Inspiration", "Inspiration"),
                    ("Latest_Posts", "Latest_Posts"),
                ],
                max_length=100,
            ),
        ),
    ]
